var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var MonsterCfg = (function () {
    function MonsterCfg() {
    }
    MonsterCfg.cfgs = [
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 1,
            skillId: 0,
            model: "monster_1"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 2,
            skillId: 0,
            model: "monster_2"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 3,
            skillId: 0,
            model: "monster_3"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 4,
            skillId: 0,
            model: "monster_4"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 5,
            skillId: 0,
            model: "monster_5"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 6,
            skillId: 0,
            model: "monster_6"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 7,
            skillId: 0,
            model: "monster_7"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 8,
            skillId: 0,
            model: "monster_8"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 1,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 9,
            skillId: 0,
            model: "monster_9"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 10,
            skillId: 0,
            model: "s_monster_1"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 11,
            skillId: 0,
            model: "s_monster_2"
        },
        ,
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 12,
            skillId: 0,
            model: "s_monster_3"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 13,
            skillId: 0,
            model: "s_monster_4"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 14,
            skillId: 0,
            model: "s_monster_5"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 15,
            skillId: 0,
            model: "s_monster_6"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 16,
            skillId: 0,
            model: "s_monster_7"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 17,
            skillId: 0,
            model: "s_monster_8"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 18,
            skillId: 0,
            model: "s_monster_9"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 19,
            skillId: 0,
            model: "s_monster_10"
        },
        {
            name: "名字",
            level: 1,
            atktype: 1,
            atkDis: 50,
            type: 2,
            spd: 30,
            atk: 100,
            hp: 500,
            id: 20,
            skillId: 0,
            model: "s_monster_11"
        }
    ];
    return MonsterCfg;
}());
__reflect(MonsterCfg.prototype, "MonsterCfg");
//# sourceMappingURL=MonsterCfg.js.map