var RES_RESOURCE = "resource/";
var EFFECT = "resource/res/animate/";
var SKILL = EFFECT + "skill103/";
var MONSTER = "resource/res/animate/monster/";
var MAP_DIR = RES_RESOURCE + "map/";
var CFG_DIR = RES_RESOURCE + "config/";
var DEFAULT_FONT = RES_RESOURCE + "res/font/yt.ttf";
var RES_AUDIO = "resource/res/audio/";
var SKILL_EFF = EFFECT + "skill/";
//# sourceMappingURL=ResDir.js.map