var RES_RESOURCE = "resource/";
var COMMON_DIR = "resource/res/common/";
var EFFECT = "resource/res/animate/";
var ITEM = "resource/res/item/";
var MAP_DIR = RES_RESOURCE + "map/";
var CFG_DIR = RES_RESOURCE + "config/";
var SKILL_EFF = EFFECT + "skill/";
var EFFROLESHOW = EFFECT + "show/";
var SOLDIER = EFFECT + "soldier/";
var DEFAULT_FONT = RES_RESOURCE + "res/font/hwkt.ttf";
//# sourceMappingURL=ResDir.js.map