/**
 * 关卡配置
 */
class LevelCfg {
	public static readonly levelCfg:LevelItemCfg[] = [
		{
			name:"张纯",
			job:3,
			res:"level_1_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI],
			skillRes:"",
			campaigName:"battle_title_1_png",
			headIcon:"level_1_head_png",
			level:1
		},
		{
			name:"管亥",
			job:4,
			res:"level_2_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI,SoldierType.SOLDIER_QIANG],
			skillRes:"",
			campaigName:"battle_title_2_png",
			headIcon:"level_2_head_png",
			level:2
		},
		{
			name:"曹操",
			job:5,
			res:"level_3_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI],
			skillRes:"",
			campaigName:"battle_title_3_png",
			headIcon:"level_3_head_png",
			level:3
		},
		{
			name:"张纯",
			job:3,
			res:"level_1_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI],
			skillRes:"",
			campaigName:"battle_title_1_png",
			headIcon:"level_1_head_png",
			level:4
		},
		{
			name:"管亥",
			job:4,
			res:"level_2_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI,SoldierType.SOLDIER_QIANG],
			skillRes:"",
			campaigName:"battle_title_2_png",
			headIcon:"level_2_head_png",
			level:5
		},
		{
			name:"曹操",
			job:5,
			res:"level_3_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI],
			skillRes:"",
			campaigName:"battle_title_3_png",
			headIcon:"level_3_head_png",
			level:6
		},
		{
			name:"张纯",
			job:3,
			res:"level_1_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI],
			skillRes:"",
			campaigName:"battle_title_1_png",
			headIcon:"level_1_head_png",
			level:7
		},
		{
			name:"管亥",
			job:4,
			res:"level_2_idle",
			soldierEnum:[SoldierType.SOLDIER_QIANG,SoldierType.SOLDIER_DAO,SoldierType.SOLDIER_QI,SoldierType.SOLDIER_QIANG],
			skillRes:"",
			campaigName:"battle_title_2_png",
			headIcon:"level_2_head_png",
			level:8
		}
	]
}